export const peopleConstants = {
    FETCH_REQUEST: 'PEOPLE_FETCH_REQUEST',
    FETCH_SUCCESS: 'PEOPLE_FETCH_SUCCESS',
    FETCH_FAILURE: 'PEOPLE_FETCH_FAILURE',

    FETCH_SINGLE_REQUEST: 'PEOPLE_FETCH_SINGLE_REQUEST',
    FETCH_SINGLE_SUCCESS: 'PEOPLE_FETCH_SINGLE_SUCCESS',
    FETCH_SINGLE_FAILURE: 'PEOPLE_FETCH_SINGLE_FAILURE',

    ADD_REQUEST: 'PERSON_ADD_REQUEST',
    ADD_SUCCESS: 'PERSON_ADD_SUCCESS',
    ADD_FAILURE: 'PERSON_ADD_FAILURE',

    EDIT_REQUEST: 'PERSON_EDIT_REQUEST',
    EDIT_SUCCESS: 'PERSON_EDIT_SUCCESS',
    EDIT_FAILURE: 'PERSON_EDIT_FAILURE'
};